trigger:
- master   # branch to trigger on

pool:
  name: 'Default'   # use default agent pool

steps:
- script: |
    echo "API call successful!"
    echo "Pipeline executed successfully"
  displayName: 'Run API Call Success Strings'
